# Generated by Django 5.0.6 on 2024-09-09 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_System', '0002_alter_profile_image_follow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
