# Generated by Django 5.0.6 on 2024-09-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_System', '0003_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.URLField(default='https://i.ibb.co.com/Jkcfb1W/png-transparent-user-profile-computer-icons-login-user-avatars-thumbnail.png', max_length=300),
        ),
    ]
