# Generated by Django 5.0.6 on 2024-09-13 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth_System', '0004_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(blank=True, max_length=300, null=True)),
                ('video', models.URLField(blank=True, max_length=300, null=True)),
                ('caption', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('post_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to='Auth_System.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CommentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth_System.profile')),
                ('commentpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='POST_CRUD.createpost')),
            ],
        ),
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth_System.profile')),
                ('likepost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='POST_CRUD.createpost')),
            ],
        ),
    ]
