# Generated by Django 5.0.6 on 2024-09-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST_CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='createpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
